### ISSUE TITLE
[BUG] "stream errored out" when using Baileys v6.2.1 or below

### ISSUE THREAD

**Issue by iosahil** [WhiskeySockets/Baileys#130]
**Original Issue:** #107 

Since, the `stream errored out` error is happening again while using Baileys `v6.2.1` or `version: [2, 2323, 4]`, this issue is being reopened.
NOTE: Some work-though solutions have also been discussed in #107

**Comment by marcioscf** [comment]
Any news?
I tried upgrading my version to many new versions and none worked.
I would prefer to not downgrade and upgrade the version of the package.

**Comment by zennn08** [comment]
Try to update your WhatsApp App

**Comment by Ahmadhrp** [comment]
my program stop working using baileys v4 or v5. any suggestions sir?

**Comment by elmasse** [comment]
I have been dealing with this all week. 
The issue is persistent with 6.2.1 and even changing the version to whatever you want to try. I also updated my WhatsApp version in my phone.

After linking a QR code I got a 515 stream error and the connection is closed. The WhatsApp app keeps the qr reader opened, and nothing happens in the phone.

**A little hack that worked for me** keep the WhatsApp app open, and then restart the connection right away (make a new call to whatever function you have calling `makeWASocket`).

**Comment by akimabs** [comment]
same with me, any update ?

**Comment by eldoncosta1** [comment]
any update?

**Comment by aayush-farmart** [comment]
any update on this issue?

**Comment by p-ugulino** [comment]
Bumping

**Comment by EcoArtGrafica** [comment]
I have the same problem, any solution?
