### ISSUE TITLE
App state key not present!

### ISSUE THREAD

**Issue by vishwajit76** [WhiskeySockets/Baileys#243]
When I tried to change profile name using Mobile API, **"App state key not present!"** error occurred.

`await this.instance.sock?.updateProfileName(name);`

**Comment by PurpShell** [comment]
Hi. I think this issue is the case because the app state keys (keys that are needed to make changes to your whatsapp app settings across linked devices and the mobile app) are not there or haven't synced yet. In this case, i suggest you make sure you are making this call after the session is open and ready
