### ISSUE TITLE
[BUG] Browser 

### ISSUE THREAD

**Issue by Riders004** [WhiskeySockets/Baileys#481]
Browser Logo Not Showing Any Idea To Add Browser Logo

**Comment by allburov** [comment]
Hi! There's old issue about that https://github.com/WhiskeySockets/Baileys/issues/228

>this is not a bug. the new version of WhatsApp doesn't show the browser anymore. it will only show the OS name.

I don't think as @bentacos mentioned https://github.com/WhiskeySockets/Baileys/issues/228#issuecomment-1625710441

Because if you change https://github.com/WhiskeySockets/Baileys/blob/e24947e55ad6e3370de867b258bb33bb9e828c56/src/Utils/validate-connection.ts#L94C3-L94C56
to `proto.DeviceProps.PlatformType.CHROME` - it does show "browser" icon

So if I set `browser: ["MyAwesomeApp", "Chrome", "118.0.0.0"]` and change `platformType` to `CHROME` - it does show icon + `Google Chrome (MyAwesomeApp) with the icon  (screenshot attached below)

So what we need to do is to find right "platformType" based on `browser[1]` argument or fallback to `DESKTOP` if not found
https://github.com/WhiskeySockets/Baileys/blob/e24947e55ad6e3370de867b258bb33bb9e828c56/src/Utils/validate-connection.ts#L92-L96
https://github.com/WhiskeySockets/Baileys/blob/e24947e55ad6e3370de867b258bb33bb9e828c56/WAProto/WAProto.proto#L533-L558

I'll open PR with the suggested changes a bit later

---

![Screenshot_2023-11-05-19-05-01-396_com whatsapp](https://github.com/WhiskeySockets/Baileys/assets/4376814/89a1c694-f09e-4225-9839-e4fa03875102)

**Comment by panalgin** [comment]
Hello, thanks for the addition. Is this merged to main? I desperately need it

**Comment by Riders004** [comment]
> Hello, thanks for the addition. Is this merged to main? I desperately need it

It's not merged on main due to any update isn't come from last 2 month's

If you want to use  you can use [@queenanya/baileys](https://www.npmjs.com/package/@queenanya/baileys) I updated on it

**Comment by panalgin** [comment]
Thanks for the heads up, do you have the seperate github project for this? I would like to fork and append my own changes on top of it, personally I don't use npmjs, thank you so much in advance

**Comment by Riders004** [comment]
> Thanks for the heads up, do you have the seperate github project for this? I would like to fork and append my own changes on top of it, personally I don't use npmjs, thank you so much in advance

Actually I haven't seprate project I make issue and I got solution so I forked the whiskeysockets Baileys and add the browser in that and then I updated in npm if you don't use npm package I send a in zip file if you want
